all: planificador core distribuidor

planificador: planificador.cpp
	g++ -o planificador planificador.cpp 

core: core.cpp
	g++ -o core core.cpp 

distribuidor: distribuidor.cpp
	g++ -o distribuidor distribuidor.cpp 
