all: planificador core distribuidor

planificador: planificador.cpp
	g++ -I include -o planificador planificador.cpp 

core: core.cpp
	g++ -I include -o core core.cpp 

distribuidor: distribuidor.cpp
	g++ -I include -o distribuidor distribuidor.cpp 
