all: buscador cache motorDeBusqueda

buscador: buscador.cpp
	g++ -o buscador buscador.cpp

cache: cache.cpp
	g++ -o cache cache.cpp

motorDeBusqueda: motorDeBusqueda.cpp
	g++ -o motorDeBusqueda motorDeBusqueda.cpp
